# Generated by Django 5.1.7 on 2025-12-05 15:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('number', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('country_code', models.CharField(max_length=10)),
                ('type', models.CharField(choices=[('emergency', 'Emergency'), ('embassy', 'Embassy'), ('helpline', 'Helpline')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
