# Generated by Django 5.1.7 on 2025-12-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guide',
            name='category',
            field=models.CharField(choices=[('settlement', 'Settlement'), ('career', 'Career'), ('academic', 'Academic'), ('other', 'Other')], default='settlement', max_length=20),
        ),
    ]
