# Generated by Django 5.1.7 on 2025-12-05 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlacesCache',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('raw_response', models.JSONField()),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('place_type', models.CharField(max_length=50)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
